### ISSUE TITLE
can't edit or delete services or categories

### ISSUE THREAD

**Issue by carmatana** [igorsheg/astro#1]
Nice dashboard, I liked its look and simplcity, thanks

I can't find the option to edit or delete services/categories

**Comment by geekedtv** [comment]
Can't add notes. The button just does nothing. Using Firefox. Looks good though. Needs to work and I understand it's new but there's still bugs.

**Comment by carmatana** [comment]
> Happy to update that the latest commit adds the ability to edit, delete and monitor services & categories!
> 
> Feel free to update on your experience :)

Thanks ! working ok editing, deleting and monitoring !
