### ISSUE TITLE
Arm64 support?

### ISSUE THREAD

**Issue by walkxcode** [igorsheg/astro#3]
Any plans on adding ARM64 support? I would love to run this on my raspberry pi 4 8gb!

**Comment by igorsheg** [comment]
Hey!

I'm cute my working on delivering a smaller, less cluttered docker images, will definitely add ARM as well.

**Comment by geekedtv** [comment]
> 
> 
> _also please stop promoting your dashboard on reddit you've promoted in on 3 of my posts now it's quite annoying._

This too.

**Comment by igorsheg** [comment]
> Any plans on adding ARM64 support? I would love to run this on my raspberry pi 4 8gb!

Happy to update that ARM64 images are here!

**Comment by walkxcode** [comment]
❤️
